version: "3.8"

services:
  web:
    build:
      context: ./source
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./source:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_name
      MYSQL_USER: database_user
      MYSQL_PASSWORD: database_password
    ports:
      - "3308:3306"
    volumes:
      # - mysql_data:/var/lib/mysql
      - ./mysql_data/db.sql:/docker-entrypoint-initdb.d/db.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db

volumes:
  db_data:
